<?php
$z[0]=Array("arcurl","",113,128);
$z[0][4]=array();
$z[1]=Array("litpic","",141,156);
$z[1][4]=array();
$z[2]=Array("pubdate","",522,574);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[3]=Array("arcurl","",662,677);
$z[3][4]=array();
$z[4]=Array("description","",791,841);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,250)";
$z[5]=Array("arcurl","",887,902);
$z[5][4]=array();

?>