<div class="col-lg-4 col-md-4"> 
        <div class="single-blog-inner"> 
          <div class="post-image"> <a href="[field:arcurl/]"> <img src="[field:litpic/]" alt=""> </a>
            <div class="post-date">
              <p><span>[field:pubdate function='strftime("%m-%d",@me)'/]</span>[field:pubdate function='strftime("%Y",@me)'/]</p>
            </div>
          </div>
          <div class="post-content">
            <div class="post-details">
              <div class="post-title">
                <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
              </div>
              <p>[field:description function='cn_substr(@me,170)'/]...</p>
              <a class='blog-btn' href="[field:arcurl/]">Read More</a> </div>
          </div>
        </div> 
      </div>