<?php
$z[0]=Array("global","",983,1004);
$z[0][4]=array();
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",1078,1099);
$z[1][4]=array();
$z[1][4]['name']="cfg_yx";
$z[2]=Array("global","",1168,1189);
$z[2][4]=array();
$z[2][4]['name']="cfg_dz";
$z[3]=Array("type","<li><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1747,1841);
$z[3][4]=array();
$z[3][4]['typeid']="1";
$z[4]=Array("global","",2404,2430);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",2499,2523);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";

?>