<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='active'\":@me=\"\";",783,873);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channelartlist","\r\n                      <li class=\"{dede:field name='currentstyle'/}\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                        <ul>\r\n                          {dede:channel type='son' noself='yes'}\r\n                          <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n             			  {/dede:channel}\r\n                        </ul>\r\n                      </li>\r\n                      ",1113,1619);
$z[1][4]=array();
$z[1][4]['row']="10";
$z[1][4]['typeid']="top";

?>