<?php
$z[0]=Array("global","",217,243);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",284,311);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",351,381);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",988,1023);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n      <div class=\"col-lg-4 col-md-4\"> \r\n        <div class=\"single-blog-inner\"> \r\n          <div class=\"post-image\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:litpic/]\" alt=\"\"> </a>\r\n            <div class=\"post-date\">\r\n              <p><span>[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span>[field:pubdate function='strftime(\"%Y\",@me)'/]</p>\r\n            </div>\r\n          </div>\r\n          <div class=\"post-content\">\r\n            <div class=\"post-details\">\r\n              <div class=\"post-title\">\r\n                <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n              </div>\r\n              <p>[field:description function='cn_substr(@me,170)'/]...</p>\r\n              <a class='blog-btn' href=\"[field:arcurl/]\">Read More</a> </div>\r\n          </div>\r\n        </div> \r\n      </div>\r\n      ",18927,19803);
$z[4][4]=array();
$z[4][4]['row']="3";
$z[4][4]['titlelen']="60";
$z[4][4]['typeid']="1";
$z[5]=Array("include","",20408,20443);
$z[5][4]=array();
$z[5][4]['filename']="foot.htm";

?>