<?php
$z[0]=Array("global","",289,314);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("arclist","\r\n                <li>\r\n                  <div class=\"latest-post-wrap media\">\r\n                    <div class=\"latest-post-img\"> <img src=\"[field:litpic/]\" alt=\"\"> </div>\r\n                    <div class=\"latest-post-body media-body\">\r\n                      <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                    </div>\r\n                  </div>\r\n                </li>\r\n                ",848,1303);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['titlelen']="46";

?>